name: passwords
description: Keychain app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  uuid: ^2.0.4
  flutter_secure_storage: ^3.3.3
  provider: ^4.0.5
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0

flutter:
  uses-material-design: true
  fonts:
    - family: PwdIcons
      fonts:
        - asset: fonts/PwdIcons.ttf
